# 配置文件

# 全局快捷键配置
HOTKEY_MODIFIERS = ['ctrl', 'shift']
HOTKEY_KEY = 'a'

# LMStudio API配置
LMSTUDIO_API_BASE = "http://localhost:1234/v1"
LMSTUDIO_MODEL = "gemma-4-e4b-it"
LMSTUDIO_TEMPERATURE = 0.7
LMSTUDIO_MAX_TOKENS = 900

# 语音识别配置
SPEECH_LANGUAGE = 'zh-CN'
PHRASE_TIME_LIMIT = 2
STRIP_TRAILING_PERIOD = True
FILTER_FILLER_WORDS = True

# 界面配置
WINDOW_WIDTH = 600
WINDOW_HEIGHT = 400
WINDOW_OPACITY = 0.95

# 对话配置
MAX_HISTORY_LENGTH = 10
